language: php

php:
    - "7.3"
    - "7.4"

services:
    - mysql
    - memcached

env:
    - MEMCACHED__HOST=localhost WP_VERSION=latest WP_MULTISITE=0 #Current stable release

before_install:
    - sudo apt-get install gcc make autoconf libc-dev pkg-config
    - sudo apt-get install zlib1g-dev
    - pecl channel-update pecl.php.net
    - pecl config-set preferred_state beta
    - echo 'yes' | pecl install memcache-4.0.5.2

install:
    - composer update --prefer-dist --prefer-stable

before_script:
    - memcached -p 11212 -d
    - "./bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION"
    - export COMPOSER_BIN_DIR="$HOME/.config/composer/vendor/bin"
    - export PATH="$COMPOSER_BIN_DIR:$PATH"

script:
    - ./vendor/bin/phpunit

sudo: false
